
# generated by Buildyard, do not edit. Sets FOUND_REQUIRED if all required
# dependencies are found. Used by Buildyard.cmake
set(FIND_REQUIRED_FAILED)
find_package(libzmq 4 QUIET)
if(NOT libzmq_FOUND AND NOT LIBZMQ_FOUND)
  set(FIND_REQUIRED_FAILED "${FIND_REQUIRED_FAILED} libzmq")
endif()
if(FIND_REQUIRED_FAILED)
  set(FOUND_REQUIRED FALSE)
else()
  set(FOUND_REQUIRED TRUE)
endif()